Fix timestamp conversion
strapi/migration-scripts pull request #13
Opened 2022-05-26 09:36 UTC by laurenskling

omit timestamps after converting them to sql timestamps. As researched in https://github.com/strapi/migration-scripts/issues/12

2022-05-30 14:06 UTC, alexandrebodin requested changes

2022-05-30 14:06 UTC, alexandrebodin commented on v3-mongodb-v3-sql/transform.js
> +        model.options.timestamps.includes('createdAt'))
actually this was intended as some users might already have customized the fields to be created_at so your fix will break that usecase. I will probably rewrite part of it anyway and push a bit later if you don't mind

2022-05-30 19:19 UTC, alexandrebodin commented
Hey I rewrote this part of code can you try it and let me know if that works for you ?

2022-05-31 12:01 UTC, alexandrebodin commented
Going to close this PR for now let me know if the fix worked when you have time :)

2022-05-31 12:01 UTC, closed without merging

2022-06-13 11:33 UTC, laurenskling commented
I tried your code and it worked perfectly right away. Thanks for the work